### ISSUE TITLE
Game details don't look right

### ISSUE THREAD

**Issue by richnsim** [djlauk/tecla-php#59]
**What I did**
On 'Home' klick on an available slot when already having a game booked.

**What happened**
Only text without much Layout is displayed (purpose or missing?)
It says: "Your next game is: " (with no reference).

![grafik](https://user-images.githubusercontent.com/37136857/85627387-b22a5d00-b66e-11ea-9092-19d127b4e978.png)

**What should have happened**
Normal 'Game Detail' screen with "Your next game is: x vs. y on someday at sometime"

**Comment by djlauk** [comment]
Good news: I could reproduce this, but not with every available slot.

Bad news: I have no clue, yet, what might be going on.

**Comment by djlauk** [comment]
Found and fixed online already.

Now checking if the same error occurs in other places...
