### ISSUE TITLE
User Name Change

### ISSUE THREAD

**Issue by richnsim** [djlauk/tecla-php#71]
Should a user really be able to change his name by himself?

Changing the E-Mail address is fine, but we don't want user to be able to hide behind nicknames like 'Superstar 81' or use fake names like 'Andrey Agassi'.

If ever someone should want to change his/her name (i.e. due to marriage) this is no big deal for an admin.

**Comment by djlauk** [comment]
Playing devil's advocate: Same could be said about the email address, too. Question is, how much work do you want to load on the admins.

Honestly though, I think with a club of this size, it's nothing the admins wouldn't be able to handle...

So, just tell me:

1.  Should the user be able to change the display name?
2.  Should the user be able to change the email address?

And then I'll make changes accordingly.

**Comment by richnsim** [comment]
1. Should the user be able to change the display name? => NO
2. Should the user be able to change the email address? => YES

(No one sees the email except the admins and it's not linked to anything except login, so who cares if someone puts in 'my.fakename@fakemail.com')
