### ISSUE TITLE
Double Logout causes DB access error

### ISSUE THREAD

**Issue by richnsim** [djlauk/tecla-php#74]
**What I did**
Log in twice on same browser (Chrome) with same user in different tabs.
Log out on first tab => ok
Log out on second tab => error message

**What happened**
When logging out for the second time, a message is displayed in the browser:
"Error during DB access"

![image](https://user-images.githubusercontent.com/37136857/86212820-09ea2c00-bb79-11ea-899b-3da2b5681a15.png)

**What should have happened**
Showing default home screen (not logged in)

**Note**
I don't think it's worth spending time on this issue. I just put it here so we know it happened before if other people stumble across it or it occurs in other situations too.

**Comment by djlauk** [comment]
I agree, this is a bug. I agree, it's low priority 😉 

Still, I have a strong hunch, what's going on, and should be able to fix it quickly.
