### ISSUE TITLE
Password Reset fails

### ISSUE THREAD

**Issue by richnsim** [djlauk/tecla-php#81]
Clicking the "Reset Password" button in the user view produces the following error:

`{ "type": 1, "message": "Uncaught Error: Call to undefined function widgetInput() in \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/views\/user\/reset-password.php:17\nStack trace:\n#0 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/vendor\/Lime\/App.php(672): include()\n#1 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/controllers\/user.php(139): Lime\\App->render('views\/user\/rese...', Array)\n#2 [internal function]: Lime\\App->tecla\\{closure}(Array)\n#3 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/vendor\/Lime\/App.php(1136): call_user_func(Object(Closure), Array)\n#4 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/vendor\/Lime\/App.php(1109): Lime\\App->render_route('\/users\/reset-pa...', Array)\n#5 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/vendor\/Lime\/App.php(1034): Lime\\App->dispatch('\/users\/reset-pa...')\n#6 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/index.php(47): Lime\\App->run()\n#7 {main}\n thrown", "file": "\/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/views\/user\/reset-password.php", "line": 17 }`

Error occurs on Chrome, Edge, IE for any user.

**Comment by djlauk** [comment]
Thanks for reporting. Fixed and deployed online.
