### ISSUE TITLE
Adding new users fails

### ISSUE THREAD

**Issue by richnsim** [djlauk/tecla-php#82]
The "ADD USER" button on the "https://tennis.sportclub-psi.ch/users" page generates the following error:

`{ "type": 1, "message": "Uncaught Error: Call to undefined function widgetInput() in \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/views\/user\/add.php:17\nStack trace:\n#0 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/vendor\/Lime\/App.php(672): include()\n#1 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/controllers\/user.php(77): Lime\\App->render('views\/user\/add....', Array)\n#2 [internal function]: Lime\\App->tecla\\{closure}(Array)\n#3 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/vendor\/Lime\/App.php(1136): call_user_func(Object(Closure), Array)\n#4 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/vendor\/Lime\/App.php(1055): Lime\\App->render_route('\/users\/add', Array)\n#5 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/vendor\/Lime\/App.php(1034): Lime\\App->dispatch('\/users\/add')\n#6 \/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/index.php(47): Lime\\App->run()\n#7 {main}\n thrown", "file": "\/home_pr5\/s\/p\/sportclub-psi.ch\/htdocs\/tennis\/views\/user\/add.php", "line": 17 }`

The error looks similar to #81 (Password Reset fails).

**Comment by djlauk** [comment]
I deployed the fix manually. It looks OK to me now.
